api-version: v1Beta
environment:
  - key: EXCHANGE_ID
    value: autofill
  - key: EXCHANGE_INSTANCE
    value: prod
  - key: EXCHANGE_ACCOUNT
    value: 9019590001
  - key: AZURE_CONNECT_STR
    value-source: SYSTEM_ENV
  - key: INSTRUMENTS_TO_CACHE
    value: Phemex/BTCUSD
  - key: EXTRA_OUTPUTS
    value: TradeFlows,BollingerBands,PnL
strategies:
  - name: BollingerBands
    module: bbands1
    strategy-class: BollingerBandsStrategy1
    environment:
      - key: TRADING_INSTRUMENT
        value: Phemex/BTCUSD
      - key: BBANDS_BIN_MINUTES
        value: 5
      - key: BBANDS_WINDOW
        value: 12
      - key: BBANDS_NUM_STD
        value: 3
      - key: BBANDS_STOP_STD
        value: 1
      - key: BBANDS_QTY
        value: 100000
      - key: TRADE_FLOW_REVERSAL_QTY
        value: 10000