api-version: v1Beta
environment:
  - key: EXCHANGE_ID
    value: autofill
  - key: EXCHANGE_INSTANCE
    value: prod
  - key: AZURE_CONNECT_STR
    value-source: SYSTEM_ENV

  - key: PEG_INSTRUMENT
    value: BTCUSD
  - key: PEG_TYPE
    value: Near
  - key: PEG_SIDE
    value: Buy
  - key: PEG_QTY
    value: 1
