apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
type: Opaque
data:
  postgres-password: "cG9zdGdyZXM="
  serenity-password: "c2VyZW5pdHlkYg=="
  sharadar-password: "c2hhcmFkYXJkYg=="
