apiVersion: apps/v1
kind: Deployment
metadata:
  name: phemex-fh-btcusd
  labels:
    app: phemex-fh-btcusd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phemex-fh-btcusd
  template:
    metadata:
      labels:
        app: phemex-fh-btcusd
    spec:
      containers:
        - name: phemex-fh-btcusd
          image: cloudwallcapital/serenity:2020.09.29-b25
          command: ["python"]
          args: ["serenity/marketdata/fh/phemex_fh.py", "--include_symbol=BTCUSD"]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password
          volumeMounts:
            - mountPath: /behemoth
              name: behemoth 
      volumes:
        - name: behemoth
          persistentVolumeClaim:
            claimName: behemoth-pv-claim
