apiVersion: apps/v1
kind: Deployment
metadata:
  name: serenity-postfix
  labels:
    app: serenity-postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serenity-postfix
  template:
    metadata:
      labels:
        app: serenity-postfix
    spec:
      containers:
        - name: serenity-postfix
          image: cloudwallcapital/serenity-postfix:2020.12.19-b1
          ports:
            - containerPort: 25
