apiVersion: batch/v1
kind: Job
metadata:
  name: sharadar-backfill
spec:
  template:
    spec:
      containers:
        - name: sharadar-backfill
          image: cloudwallcapital/serenity:2020.12.09-b60
          command: ["python"]
          args: ["serenity/equity/batch/main.py", "--mode", "BACKFILL"]
          env:
          - name: POSTGRES_SHARADAR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: sharadar-password
          - name: QUANDL_API_KEY
            valueFrom:
              secretKeyRef:
                name: quandl-secret-config
                key: api-key

        restartPolicy: Never
  backoffLimit: 4
