apiVersion: batch/v1beta1
kind: Job
metadata:
  name: sharadar-backfill
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sharadar-backfill
            image: cloudwallcapital/serenity:2020.10.24-b52
            command: ["python"]
            args: ["serenity/equity/batch/main.py", "--mode", "BACKFILL", "--workers", "5"]
            env:
            - name: POSTGRES_SHARADAR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: sharadar-password
          restartPolicy: OnFailure
